// import "./globals.css";
import "./common.css";
import "./blog.css";
import "./home.css";
import "./gpt.css";
import "./animation.css";
import "./mobile-menu.css";
import "./uifixer.css";
import HeaderMenu from "./_headerMenu/page";
import FooterMenu from "./_footerMenu/page";
import { Suspense } from "react";
import "./inside.css";
import SeoData from "../../lib/seo";

const { title } = SeoData;
console.log(title);

 const metadata = {
  title: "Welcome to orient faiance",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="new-home-page">
        {
          <Suspense fallback={<div>Loading...</div>}>
            <HeaderMenu />

            {children}

            <FooterMenu />
          </Suspense>
        }
      </body>
    </html>
  );
}
